# Copyright 2024 Khalil Estell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: ✅ CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 0"
# fire again! 6
jobs:
  ci:
    uses: libhal/ci/.github/workflows/library_check.yml@docs
    secrets: inherit

  # deploy_all_check:
  #   uses: libhal/ci/.github/workflows/deploy_all.yml@5.x.y
  #   secrets: inherit

  # demo_check_lpc4074:
  #   uses: libhal/ci/.github/workflows/demo_builder.yml@5.x.y
  #   with:
  #     compiler_profile_url: https://github.com/libhal/arm-gnu-toolchain.git
  #     compiler_profile: v1/arm-gcc-12.3
  #     platform_profile_url: https://github.com/libhal/libhal-arm-mcu.git
  #     platform_profile: v1/lpc4074
  #   secrets: inherit

  # demo_check_lpc4078:
  #   uses: libhal/ci/.github/workflows/demo_builder.yml@5.x.y
  #   with:
  #     compiler_profile_url: https://github.com/libhal/arm-gnu-toolchain.git
  #     compiler_profile: v1/arm-gcc-12.3
  #     platform_profile_url: https://github.com/libhal/libhal-arm-mcu.git
  #     platform_profile: v1/lpc4078
  #   secrets: inherit

  # demo_check_stm32f103c8:
  #   uses: libhal/ci/.github/workflows/demo_builder.yml@5.x.y
  #   with:
  #     compiler_profile_url: https://github.com/libhal/arm-gnu-toolchain.git
  #     compiler_profile: v1/arm-gcc-12.3
  #     platform_profile_url: https://github.com/libhal/libhal-arm-mcu.git
  #     platform_profile: v1/stm32f103c8
  #   secrets: inherit

  # demo_check_micromod:
  #   uses: libhal/ci/.github/workflows/demo_builder.yml@5.x.y
  #   with:
  #     compiler_profile_url: https://github.com/libhal/arm-gnu-toolchain.git
  #     compiler_profile: v1/arm-gcc-12.3
  #     platform_profile_url: https://github.com/libhal/libhal-micromod.git
  #     platform_profile: v1/mod-stm32f1-v5
  #   secrets: inherit
